sudo: false
language: python
matrix:
  include:
  - os: linux
    python: '2.7'
    env: CONDA=true
  - os: linux
    python: '3.6'
    env: CONDA=true
before_install:
- if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then lsb_release -a ; fi
install:
- pip install -e .
- pip install pytest-cov
- if [[ "$TRAVIS_PYTHON_VERSION" == 2.7 ]]; then pip install ipython==5.8.0 ; fi
- pip install nbval
script:
- pytest --cov=galgebra --nbval examples/ipython/ test --current-env 
after_success:
- pip install codecov
- codecov
env:
  global:
  - secure: aMFLWySkx+e2z0HOUg+jziFzvaTrZfw2t1tyRr3gUouEiiNiDVMRQ8hc46iSZLYITzNTX0d11iTrJObF4Cn3cnHZrAeUDu73xzosELb0Abt8/wIPGw7ltWljz8gmV++EyK1bW9xkBj7Zebjm6Wl/usCt0sUbpm5vhJbwE0qgHbeLalXFX17JDunBmVnMT6S1M62r9REvDh9DvQdunbKpUr5cDqGPmG2RVVjYOiz3vUB62d4blgB349gSygLZjWeXPL9VzaR5al9psGypeHJWc3sWRowXUTVYkCJ+2vXynZjsEyPfhZYIK2s/Dm7hqqqH9NmqMpi57ml3lSBPBfAV6VlcZJxYYY0HR8c72kSGq87bEIRjgkXA25Po6ad7DsyMnwtKiy6Eu2SGWfPa8MTAe5rDQrXr7eqNpo3mr5o6lVtWpXqWEi8NtJ6a5rVcKcHKoffn2ZHUzQvFscaT9sr3xIUtUcIzq3JsJFYHphMKEqO7Fdzcm50lKXqc4Q6VEE/l0tEzwjId5/Wfxf6mmc5S7JHGGQDzvp8KuZjjIkzN/lgpMBNasQq85+aBVQ7tkv0UetgvB0f/jgH2x4vGDiB1C0J+VzlILawcqPFBIKCsN3xmblPYFwrMWb84C9579Ze5k25xFlA3m2xWiue58sSKav1CJhRdMbxmx1hRTv8rOfE=
  - secure: Ygar4HcsSsMw4DQCQwXDEBppsoFwXLhkFp0HWzZ2WJpKu3uXoCTt2uxH+RvvQBLp9d+EsmP7QnPdLh1CIbITw3ybgv/bOACZaIeM4JfFHzPX4u5E0eE2S5qnkQvJ7aq7lY1TLXXIw7GF9HFJqN42qvx4FNHXDpzd+tlAgDJe/LyocYAzkH4XZ4b8SICsDKVaylTbv1NwWU9gUDqv+0c50e1wcoVnHR4yWAFe+y+BTbUrWTCiLsn5DMgZJbbgD8B3TjBEWcaDD5t9rA1aopIaNuFeIIi49KlZWgnqRAg0nwS0NdbhpqWqAateQMorhx6ZNxWlShRxhE3n51+wUOtcXjJ24/3WZTdaq6oXUAScNNe5SBKsSx2V7XUNdK7oIGHYU6bQNln8o03mBzPp5fmGj+71/pyXsqwRUqTPBi6SU+WeVA9fMuI4s6K/up5bSJ7II+/0fvPgwrQficnW8U+3GR6gxXi4d5D9MrJWSsqkab+QfSAuJ0bwEZOhX1MKYqCBHQVxKGxV686L1rYalGYSqkMZEGwmbwAnU41KzIPKQW3yuNu5ytukoFbI9ndtbx87qImxn++TD4UtClGcOJoL98N+OrZnnxJAhkZm8Ork8s8h0uGkKRfnfcBqZVOP7ZCbQD/MNK/kxg6GWqCOY4h9PdcjX0fOGA1Icw7AxGRlzg0=
deploy:
  provider: pypi
  user: hugohadfield
  password:
    secure: TvP53LZ0AJlNa/u2T0+eOYKujO4llmsouGkH357JZXGNgNXc4Xmdh8mi9vEDeJ+xjDrBjSkQxsTSunT1g9fcLUitE99adULpOahi+2zf+SVeAyhyHNdb5ZsKe5GIhRj+zJ49B2tXXwHKbwmJ+lfDVcyAkncKbm52/0eUlS/zwgjEgy++0MYq/KHPh+qIJnaKHY2jNp0FijqUIUIkRMRwOqo4WYRoBOyHM2lo1vpov4UUvCTeE5fCaef45F+CHm2+or1C5MmxHOXPXKW6zOYUzL4Q/xduT201oGS3QIPQvZDCf5+0UYWatruKWCEQu9EBCcAH8rqbhOrOZK8cCITHbG9y9jvrr+UKcK1Nj97UL/ZtQ7vrg9EYC4MeB1kPC8U/VL3pCVq2my2A6K6X50+pR9D+7+3jHSc3gGZiC2xt7TReh1LyRNNDUpYVHyINNFUif0+5y4hq5xFFh8oYQ22dKaSa2svxd5MXKWcL6qipa5acYGZG9asoRL/3p/YhEYbEgQDzM2EubTitB4JEjWZTf3HpUUZCjXA+DYCl4yvfNTz0BDm3HbL1oDaE32tnFC7S+M0i6AaIWgAb/pOPH6R9SLIjy82FZJtB3VOEOgD86IoJ+Ks2OmS09XUuhtGgs3xNMYntHYiz2e/g9Iaip2zd8ddUbnRt6ah3ETlk9XPWKf0=
  on:
    tags: true
